In [22]:
import pandas as pd

df_2008 = pd.read_csv("../data/atp_matches_2008.csv")
df_2009 = pd.read_csv("../data/atp_matches_2009.csv")
df_2010 = pd.read_csv("../data/atp_matches_2010.csv")
df_2011 = pd.read_csv("../data/atp_matches_2011.csv")
df_2012 = pd.read_csv("../data/atp_matches_2012.csv")
df_2013 = pd.read_csv("../data/atp_matches_2013.csv")
df_2014 = pd.read_csv("../data/atp_matches_2014.csv")
df_2015 = pd.read_csv("../data/atp_matches_2015.csv")
df_2016 = pd.read_csv("../data/atp_matches_2016.csv")
df_2017 = pd.read_csv("../data/atp_matches_2017.csv")
df_2018 = pd.read_csv("../data/atp_matches_2018.csv")
df_2019 = pd.read_csv("../data/atp_matches_2019.csv")
df_2020 = pd.read_csv("../data/atp_matches_2020.csv")
df_2021 = pd.read_csv("../data/atp_matches_2021.csv")
df_2022 = pd.read_csv("../data/atp_matches_2022.csv")
df_2023 = pd.read_csv("../data/atp_matches_2023.csv")
df_2024 = pd.read_csv("../data/atp_matches_2024.csv")
df_2025 = pd.read_csv("../data/atp_matches_2025.csv")
df_2026 = pd.read_csv("../data/atp_matches_2026.csv")

df_pre_model = pd.concat([df_2008,df_2009,df_2010,df_2011,df_2012,df_2013,df_2014,df_2015,df_2016,df_2017,df_2018,df_2019,df_2020,df_2021,df_2022,df_2023,df_2024,df_2025,df_2026],ignore_index=True)

df_pre_model

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2008-1536,Madrid Masters,Hard,48,M,20081012,1,105208,NaN,NaN,Ernests Gulbis,R,190.0,LAT,20.1,103017,NaN,NaN,Nicolas Kiefer,R,183.0,GER,31.2,5-7 6-4 7-5,3,R64,143.0,10.0,4.0,99.0,63.0,48.0,21.0,17.0,3.0,4.0,5.0,4.0,95.0,51.0,42.0,26.0,17.0,3.0,5.0,54.0,719.0,27.0,1120.0
1,2008-1536,Madrid Masters,Hard,48,M,20081012,2,103888,NaN,NaN,Mardy Fish,R,188.0,USA,26.8,104327,NaN,Q,Steve Darcis,R,178.0,BEL,24.5,6-1 6-4,3,R64,71.0,13.0,1.0,54.0,25.0,24.0,17.0,9.0,4.0,4.0,0.0,1.0,51.0,26.0,14.0,15.0,8.0,1.0,4.0,25.0,1145.0,59.0,694.0
2,2008-1536,Madrid Masters,Hard,48,M,20081012,3,104259,NaN,NaN,Philipp Kohlschreiber,R,178.0,GER,24.9,102845,NaN,NaN,Carlos Moya,R,190.0,ESP,32.1,6-2 6-2,3,R64,66.0,3.0,1.0,47.0,28.0,22.0,12.0,8.0,1.0,1.0,3.0,3.0,58.0,36.0,19.0,8.0,8.0,5.0,9.0,31.0,1065.0,46.0,805.0
3,2008-1536,Madrid Masters,Hard,48,M,20081012,4,103852,NaN,NaN,Feliciano Lopez,L,188.0,ESP,27.0,103656,NaN,WC,Albert Montanes,R,175.0,ESP,27.8,7-6(4) 6-3,3,R64,88.0,10.0,1.0,61.0,37.0,34.0,16.0,11.0,0.0,0.0,1.0,4.0,86.0,48.0,31.0,22.0,10.0,4.0,5.0,40.0,865.0,48.0,777.0
4,2008-1536,Madrid Masters,Hard,48,M,20081012,5,103812,NaN,Q,Victor Hanescu,R,198.0,ROU,27.2,104098,NaN,NaN,Dmitry Tursunov,R,185.0,RUS,25.8,4-6 6-2 6-3,3,R64,98.0,12.0,2.0,84.0,57.0,48.0,9.0,14.0,2.0,4.0,5.0,2.0,87.0,62.0,36.0,14.0,13.0,4.0,8.0,73.0,579.0,26.0,1123.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53167,2026-M-DC-2026-WG2-PO-RSA-MNE-01,Davis Cup WG2 PO: RSA vs MNE,Hard,4,D,20260207,4,202475,NaN,NaN,Philip Henning,R,NaN,RSA,25.2,210188,NaN,NaN,Petar Jovanovic,U,NaN,MNE,22.5,6-3 6-2,3,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,317.0,160.0,1679.0,2.0
53168,2026-M-DC-2026-WG2-PO-RSA-MNE-01,Davis Cup WG2 PO: RSA vs MNE,Hard,4,D,20260207,5,209278,NaN,NaN,Alec Beckley,R,183.0,RSA,24.6,210648,NaN,NaN,Aleksa Krivokapic,U,NaN,MNE,22.7,7-6(3) 6-3,3,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,783.0,35.0,NaN,NaN
53169,2026-M-DC-2026-WG2-PO-THA-PUR-01,Davis Cup WG2 PO: THA vs PUR,Hard,4,D,20260207,1,210382,NaN,NaN,Maximus Jones,R,185.0,THA,21.4,214425,NaN,NaN,Yannik Alvarez,U,NaN,PUR,17.3,6-1 6-2,3,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,304.0,172.0,NaN,NaN
53170,2026-M-DC-2026-WG2-PO-THA-PUR-01,Davis Cup WG2 PO: THA vs PUR,Hard,4,D,20260207,2,208937,NaN,NaN,Kasidit Samrej,R,191.0,THA,25.0,211670,NaN,NaN,Marko Mesarovic,U,NaN,USA,NaN,6-2 6-1,3,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,395.0,120.0,1307.0,6.0
53171,2026-M-DC-2026-WG2-PO-THA-PUR-01,Davis Cup WG2 PO: THA vs PUR,Hard,4,D,20260207,4,210687,NaN,NaN,Pawit Sornlaksup,U,NaN,THA,26.4,211670,NaN,NaN,Marko Mesarovic,U,NaN,USA,NaN,2-6 6-4 [11-9],3,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,703.0,46.0,1307.0,6.0

In [23]:
df_2011.columns.tolist()        
lista = ['w_ace',
 'w_df',
 'w_svpt',
 'w_1stIn',
 'w_1stWon',
 'w_2ndWon',
 'w_SvGms',
 'w_bpSaved',
 'w_bpFaced',
 'l_ace',
 'l_df',
 'l_svpt',
 'l_1stIn',
 'l_1stWon',
 'l_2ndWon',
 'l_SvGms',
 'l_bpSaved',
 'l_bpFaced',]

In [24]:


df_pre_model["matchup_id"] = df_pre_model.apply(lambda r: f"{min(r['winner_id'], r['loser_id'])}_{max(r['winner_id'], r['loser_id'])}", axis=1)
df_pre_model

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,matchup_id
0,2008-1536,Madrid Masters,Hard,48,M,20081012,1,105208,NaN,NaN,Ernests Gulbis,R,190.0,LAT,20.1,103017,NaN,NaN,Nicolas Kiefer,R,183.0,GER,31.2,5-7 6-4 7-5,3,R64,143.0,10.0,4.0,99.0,63.0,48.0,21.0,17.0,3.0,4.0,5.0,4.0,95.0,51.0,42.0,26.0,17.0,3.0,5.0,54.0,719.0,27.0,1120.0,103017_105208
1,2008-1536,Madrid Masters,Hard,48,M,20081012,2,103888,NaN,NaN,Mardy Fish,R,188.0,USA,26.8,104327,NaN,Q,Steve Darcis,R,178.0,BEL,24.5,6-1 6-4,3,R64,71.0,13.0,1.0,54.0,25.0,24.0,17.0,9.0,4.0,4.0,0.0,1.0,51.0,26.0,14.0,15.0,8.0,1.0,4.0,25.0,1145.0,59.0,694.0,103888_104327
2,2008-1536,Madrid Masters,Hard,48,M,20081012,3,104259,NaN,NaN,Philipp Kohlschreiber,R,178.0,GER,24.9,102845,NaN,NaN,Carlos Moya,R,190.0,ESP,32.1,6-2 6-2,3,R64,66.0,3.0,1.0,47.0,28.0,22.0,12.0,8.0,1.0,1.0,3.0,3.0,58.0,36.0,19.0,8.0,8.0,5.0,9.0,31.0,1065.0,46.0,805.0,102845_104259
3,2008-1536,Madrid Masters,Hard,48,M,20081012,4,103852,NaN,NaN,Feliciano Lopez,L,188.0,ESP,27.0,103656,NaN,WC,Albert Montanes,R,175.0,ESP,27.8,7-6(4) 6-3,3,R64,88.0,10.0,1.0,61.0,37.0,34.0,16.0,11.0,0.0,0.0,1.0,4.0,86.0,48.0,31.0,22.0,10.0,4.0,5.0,40.0,865.0,48.0,777.0,103656_103852
4,2008-1536,Madrid Masters,Hard,48,M,20081012,5,103812,NaN,Q,Victor Hanescu,R,198.0,ROU,27.2,104098,NaN,NaN,Dmitry Tursunov,R,185.0,RUS,25.8,4-6 6-2 6-3,3,R64,98.0,12.0,2.0,84.0,57.0,48.0,9.0,14.0,2.0,4.0,5.0,2.0,87.0,62.0,36.0,14.0,13.0,4.0,8.0,73.0,579.0,26.0,1123.0,103812_104098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53167,2026-M-DC-2026-WG2-PO-RSA-MNE-01,Davis Cup WG2 PO: RSA vs MNE,Hard,4,D,20260207,4,202475,NaN,NaN,Philip Henning,R,NaN,RSA,25.2,210188,NaN,NaN,Petar Jovanovic,U,NaN,MNE,22.5,6-3 6-2,3,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,317.0,160.0,1679.0,2.0,202475_210188
53168,2026-M-DC-2026-WG2-PO-RSA-MNE-01,Davis Cup WG2 PO: RSA vs MNE,Hard,4,D,20260207,5,209278,NaN,NaN,Alec Beckley,R,183.0,RSA,24.6,210648,NaN,NaN,Aleksa Krivokapic,U,NaN,MNE,22.7,7-6(3) 6-3,3,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,783.0,35.0,NaN,NaN,209278_210648
53169,2026-M-DC-2026-WG2-PO-THA-PUR-01,Davis Cup WG2 PO: THA vs PUR,Hard,4,D,20260207,1,210382,NaN,NaN,Maximus Jones,R,185.0,THA,21.4,214425,NaN,NaN,Yannik Alvarez,U,NaN,PUR,17.3,6-1 6-2,3,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,304.0,172.0,NaN,NaN,210382_214425
53170,2026-M-DC-2026-WG2-PO-THA-PUR-01,Davis Cup WG2 PO: THA vs PUR,Hard,4,D,20260207,2,208937,NaN,NaN,Kasidit Samrej,R,191.0,THA,25.0,211670,NaN,NaN,Marko Mesarovic,U,NaN,USA,NaN,6-2 6-1,3,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,395.0,120.0,1307.0,6.0,208937_211670
53171,2026-M-DC-2026-WG2-PO-THA-PUR-01,Davis Cup WG2 PO: THA vs PUR,Hard,4,D,20260207,4,210687,NaN,NaN,Pawit Sornlaksup,U,NaN,THA,26.4,211670,NaN,NaN,Marko Mesarovic,U,NaN,USA,NaN,2-6 6-4 [11-9],3,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,703.0,46.0,1307.0,6.0,210687_211670

In [25]:
# 1. Extrai o ID do p1 (tudo antes do '_') diretamente da coluna de forma vetorizada
# Convertemos para string para garantir que a comparação funcione
p1_ids = df_pre_model['matchup_id'].str.split('_').str[0]

df_pre_model["p1_won"] = (df_pre_model['winner_id'].astype(str) == p1_ids).astype(int)

df_pre_model['p2_won'] = 1 - df_pre_model['p1_won']

In [26]:
# 1. Quantidade de partidas que eles já jogaram ANTES da partida atual
# O .cumcount() conta as linhas do grupo (0, 1, 2...). 
# Como a primeira linha vira 0, ele já funciona nativamente como o "passado", sem precisar de shift!
df_pre_model['total_h2h_matches'] = df_pre_model.groupby('matchup_id').cumcount()

# 2. Vitórias do Player 1 ANTES da partida atual (usando transform para não vazar o grupo)
df_pre_model['p1_h2h_wins'] = df_pre_model.groupby('matchup_id')['p1_won'].transform(lambda x: x.shift(1).cumsum()).fillna(0)

# 3. Vitórias do Player 2 ANTES da partida atual
df_pre_model['p2_h2h_wins'] = df_pre_model['total_h2h_matches'] - df_pre_model['p1_h2h_wins']

In [27]:
# 1. Total de partidas que eles jogaram antes NO PISO ATUAL da linha
df_pre_model['total_h2h_matches_surface'] = df_pre_model.groupby(['matchup_id', 'surface']).cumcount()

# 2. Vitórias do Player 1 antes NO PISO ATUAL da linha (usando transform para isolar o grupo composto)
df_pre_model['p1_h2h_wins_surface'] = df_pre_model.groupby(['matchup_id', 'surface'])['p1_won'].transform(lambda x: x.shift(1).cumsum()).fillna(0)

# 3. Vitórias do Player 2 antes NO PISO ATUAL
df_pre_model['p2_h2h_wins_surface'] = df_pre_model['total_h2h_matches_surface'] - df_pre_model['p1_h2h_wins_surface']

In [28]:
# Certifique-se de que a base está ordenada por data antes de rodar
df_pre_model = df_pre_model.sort_values('tourney_date').reset_index(drop=True)

# 1. Criamos os dados deslocados (shift) para garantir que o jogo de hoje não entre no cálculo
df_pre_model['p1_won_shifted'] = df_pre_model.groupby('matchup_id')['p1_won'].shift(1)

# Criamos um marcador de "1" para cada partida ocorrida, para contar quantas partidas aconteceram na janela
df_pre_model['match_marker_shifted'] = df_pre_model.groupby('matchup_id')['p1_won'].transform(lambda x: x.index * 0 + 1).shift(1)

# 2. Calculamos o total de partidas jogadas na janela das últimas 10
df_pre_model['total_h2h_matches_last_10'] = (
    df_pre_model.groupby('matchup_id')['match_marker_shifted']
    .rolling(window=10, min_periods=1)
    .sum()
    .reset_index(level=0, drop=True)
    .fillna(0)
)

# 3. Calculamos quantas dessas últimas 10 o Player 1 venceu
df_pre_model['p1_h2h_wins_last_10'] = (
    df_pre_model.groupby('matchup_id')['p1_won_shifted']
    .rolling(window=10, min_periods=1)
    .sum()
    .reset_index(level=0, drop=True)
    .fillna(0)
)

# 4. Por consequência, as vitórias do Player 2 são a diferença
df_pre_model['p2_h2h_wins_last_10'] = df_pre_model['total_h2h_matches_last_10'] - df_pre_model['p1_h2h_wins_last_10']

# Opcional: Limpar as colunas auxiliares de shift para não poluir o dataset
df_pre_model = df_pre_model.drop(columns=['p1_won_shifted', 'match_marker_shifted'])

df_pre_model

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,matchup_id,p1_won,p2_won,total_h2h_matches,p1_h2h_wins,p2_h2h_wins,total_h2h_matches_surface,p1_h2h_wins_surface,p2_h2h_wins_surface,total_h2h_matches_last_10,p1_h2h_wins_last_10,p2_h2h_wins_last_10
0,2008-339,Adelaide,Hard,32,A,20071231,1,103720,1.0,NaN,Lleyton Hewitt,R,180.0,AUS,26.8,104534,NaN,NaN,Dudi Sela,R,175.0,ISR,22.7,6-2 6-2,3,R32,66.0,7.0,2.0,46.0,29.0,26.0,8.0,8.0,3.0,3.0,5.0,2.0,59.0,37.0,22.0,8.0,8.0,7.0,11.0,21.0,1365.0,64.0,573.0,103720_104534,1,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2008-339,Adelaide,Hard,32,A,20071231,2,104076,NaN,NaN,Jose Acasuso,R,190.0,ARG,25.1,104268,NaN,NaN,Alejandro Falla,L,185.0,COL,24.1,6-3 7-6(3),3,R32,101.0,8.0,4.0,76.0,40.0,31.0,14.0,11.0,8.0,12.0,2.0,1.0,68.0,40.0,21.0,14.0,10.0,5.0,10.0,65.0,566.0,81.0,481.0,104076_104268,1,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,2008-339,Adelaide,Hard,32,A,20071231,3,105208,NaN,NaN,Ernests Gulbis,R,190.0,LAT,19.3,104979,NaN,Q,Andrey Golubev,R,185.0,KAZ,20.4,6-7(9) 6-4 6-2,3,R32,138.0,7.0,6.0,133.0,80.0,59.0,22.0,15.0,14.0,16.0,6.0,4.0,109.0,63.0,43.0,20.0,15.0,3.0,8.0,61.0,585.0,177.0,239.0,104979_105208,0,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,2008-339,Adelaide,Hard,32,A,20071231,4,104542,6.0,NaN,Jo-Wilfried Tsonga,R,188.0,FRA,22.7,103812,NaN,NaN,Victor Hanescu,R,198.0,ROU,26.4,6-3 4-6 7-5,3,R32,120.0,11.0,6.0,84.0,46.0,38.0,21.0,16.0,3.0,6.0,1.0,0.0,93.0,56.0,39.0,19.0,15.0,3.0,7.0,43.0,714.0,76.0,517.0,103812_104542,0,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
4,2008-451,Doha,Hard,32,A,20071231,28,104527,NaN,NaN,Stan Wawrinka,R,183.0,SUI,22.7,102860,NaN,NaN,Agustin Calleri,R,183.0,ARG,31.2,6-3 6-0,3,QF,65.0,4.0,0.0,39.0,23.0,20.0,12.0,8.0,0.0,0.0,2.0,3.0,59.0,28.0,19.0,9.0,7.0,5.0,9.0,36.0,820.0,42.0,715.0,102860_104527,0,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53167,2026-520,Roland Garros,Clay,128,G,20260525,102,212021,NaN,NaN,Martin Landaluce,R,191.0,ESP,20.3,210178,NaN,Q,Juan Carlos Prado Angelo,R,185.0,BOL,21.2,6-3 4-6 6-2 6-7(3) 6-4,5,R128,270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.0,827.0,176.0,338.0,210178_212021,0,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
53168,2026-520,Roland Garros,Clay,128,G,20260525,103,200240,NaN,NaN,Vit Kopriva,R,178.0,CZE,28.9,144895,30.0,NaN,Corentin Moutet,L,180.0,FRA,27.0,6-3 5-7 6-4 3-6 6-3,5,R128,260.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.0,856.0,34.0,1323.0,144895_200240,0,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
53169,2026-520,Roland Garros,Clay,128,G,20260525,109,210262,NaN,Q,Jaime Faria,R,188.0,POR,22.8,133430,NaN,NaN,Denis Shapovalov,L,185.0,CAN,27.1,6-4 7-5 6-4,5,R128,151.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.0,548.0,39.0,1170.0,133430_210262,0,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
53170,2026-520,Roland Garros,Clay,128,G,20260525,110,128034,NaN,NaN,Hubert Hurkacz,R,196.0,POL,29.2,144719,NaN,NaN,Jaume Munar,R,183.0,ESP,29.0,6-3 6-3 2-6 6-3,5,R128,183.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.0,600.0,41.0,1145.0,128034_144719,1,0,1,1.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0
53171,2026-520,Roland Garros,Clay,128,G,20260525,111,126207,19.0,NaN,Frances Tiafoe,R,188.0,USA,28.3,208118,NaN,NaN,Eliot Spizzirri,R,183.0,USA,24.4,6-3 6-7(5) 6-4 6-3,5,R128,176.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,1905.0,91.0,660.0,126207_208118,1,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

In [29]:
# Certifique-se de que a base está ordenada por data
df_pre_model = df_pre_model.sort_values('tourney_date').reset_index(drop=True)

# 1. Criamos os dados deslocados (shift) por matchup e superfície
df_pre_model['p1_won_shifted_surf'] = df_pre_model.groupby(['matchup_id', 'surface'])['p1_won'].shift(1)
df_pre_model['match_marker_shifted_surf'] = df_pre_model.groupby(['matchup_id', 'surface'])['p1_won'].transform(lambda x: x.index * 0 + 1).shift(1)

# 2. Total de partidas entre eles nas últimas 5 QUE FORAM NESSE PISO
df_pre_model['total_h2h_matches_last_10_surf'] = (
    df_pre_model.groupby(['matchup_id', 'surface'])['match_marker_shifted_surf']
    .rolling(window=10, min_periods=1)
    .sum()
    .reset_index(level=[0, 1], drop=True) # Remove os dois níveis do MultiIndex (matchup e surface)
    .fillna(0)
)

# 3. Vitórias do Player 1 nas últimas 10 QUE FORAM NESSE PISO
df_pre_model['p1_h2h_wins_last_10_surf'] = (
    df_pre_model.groupby(['matchup_id', 'surface'])['p1_won_shifted_surf']
    .rolling(window=10, min_periods=1)
    .sum()
    .reset_index(level=[0, 1], drop=True)
    .fillna(0)
)

# 4. Vitórias do Player 2
df_pre_model['p2_h2h_wins_last_10_surf'] = df_pre_model['total_h2h_matches_last_10_surf'] - df_pre_model['p1_h2h_wins_last_10_surf']

# Limpa colunas auxiliares
df_pre_model = df_pre_model.drop(columns=['p1_won_shifted_surf', 'match_marker_shifted_surf'])

In [31]:
import pandas as pd
import numpy as np

# Garanta que a base original está ordenada por data
df_pre_model = df_pre_model.sort_values('tourney_date').reset_index(drop=True)

# 1. Isolamos as estatísticas de quem VENCEU
vencedores = df_pre_model[[
    'tourney_date', 'winner_id', 'w_ace', 'w_df', 'w_svpt', 
    'w_1stIn', 'w_1stWon', 'w_2ndWon', 'w_SvGms', 'w_bpSaved', 'w_bpFaced'
]].rename(columns={
    'winner_id': 'player_id', 'w_ace': 'ace', 'w_df': 'df', 'w_svpt': 'svpt',
    'w_1stIn': 'first_in', 'w_1stWon': 'first_won', 'w_2ndWon': 'second_won',
    'w_SvGms': 'sv_gms', 'w_bpSaved': 'bp_saved', 'w_bpFaced': 'bp_faced'
})

# 2. Isolamos as estatísticas de quem PERDEU
perdedores = df_pre_model[[
    'tourney_date', 'loser_id', 'l_ace', 'l_df', 'l_svpt', 
    'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced'
]].rename(columns={
    'loser_id': 'player_id', 'l_ace': 'ace', 'l_df': 'df', 'l_svpt': 'svpt',
    'l_1stIn': 'first_in', 'l_1stWon': 'first_won', 'l_2ndWon': 'second_won',
    'l_SvGms': 'sv_gms', 'l_bpSaved': 'bp_saved', 'l_bpFaced': 'bp_faced'
})

# 3. Juntamos as duas tabelas e ordenamos por data
player_perf = pd.concat([vencedores, perdedores]).sort_values('tourney_date').reset_index(drop=True)

In [32]:
# Lista de colunas que vamos calcular a média
colunas_stats = ['ace', 'df', 'svpt', 'first_in', 'first_won', 'second_won', 'sv_gms', 'bp_saved', 'bp_faced']

# Criamos um DataFrame temporário para guardar as médias
medias_temporarias = pd.DataFrame(index=player_perf.index)

# Loop rápido apenas para aplicar o cálculo em cada coluna estatística
for col in colunas_stats:
    medias_temporarias[f'avg_{col}_last_15'] = (
        player_perf.groupby('player_id')[col]
        .shift(1) # Empurra para baixo (anti-vazamento)
        .rolling(window=15, min_periods=1) # Janela das últimas 15 partidas
        .mean()
        .reset_index(level=0, drop=True)
    )

# Adicionamos as médias de volta na tabela de performance dos jogadores
player_perf_final = pd.concat([player_perf[['tourney_date', 'player_id']], medias_temporarias], axis=1).fillna(0)

In [33]:
player_perf_final

,tourney_date,player_id,avg_ace_last_15,avg_df_last_15,avg_svpt_last_15,avg_first_in_last_15,avg_first_won_last_15,avg_second_won_last_15,avg_sv_gms_last_15,avg_bp_saved_last_15,avg_bp_faced_last_15
0,20071231,104098,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
1,20071231,104918,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2,20071231,103598,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
3,20071231,103781,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
4,20071231,104019,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
106339,20260525,210178,5.000000,2.0,85.000000,51.000000,36.500000,14.750000,13.0,4.500000,8.000000
106340,20260525,207985,4.400000,4.2,87.800000,54.200000,38.800000,14.200000,13.4,4.600000,8.200000
106341,20260525,200000,4.400000,4.2,87.800000,54.200000,38.800000,14.200000,13.4,4.600000,8.200000
106342,20260525,208286,5.250000,5.0,92.750000,55.750000,41.000000,15.500000,14.0,3.750000,7.250000
106343,20260525,126610,3.333333,6.0,95.333333,57.333333,41.666667,15.666667,14.0,3.666667,7.333333

In [34]:
# Descobrimos quem é o p1_id e p2_id em cada linha da base original
df_pre_model['p1_id'] = df_pre_model[['winner_id', 'loser_id']].min(axis=1)
df_pre_model['p2_id'] = df_pre_model[['winner_id', 'loser_id']].max(axis=1)

# 1. Merge para o Player 1
# O drop_duplicates garante que se ele jogou duas vezes no mesmo dia (raro, mas acontece), não duplique linhas
player_perf_final_p1 = player_perf_final.drop_duplicates(subset=['tourney_date', 'player_id'])
df_pre_model = pd.merge(
    df_pre_model, 
    player_perf_final_p1.add_prefix('p1_'), 
    left_on=['tourney_date', 'p1_id'], 
    right_on=['p1_tourney_date', 'p1_player_id'], 
    how='left'
).drop(columns=['p1_tourney_date', 'p1_player_id'])

# 2. Merge para o Player 2
player_perf_final_p2 = player_perf_final.drop_duplicates(subset=['tourney_date', 'player_id'])
df_pre_model = pd.merge(
    df_pre_model, 
    player_perf_final_p2.add_prefix('p2_'), 
    left_on=['tourney_date', 'p2_id'], 
    right_on=['p2_tourney_date', 'p2_player_id'], 
    how='left'
).drop(columns=['p2_tourney_date', 'p2_player_id'])

# Preenche eventuais vazios (primeiros jogos da história do jogador) com 0
colunas_novas = [f'p1_avg_{c}_last_15' for c in colunas_stats] + [f'p2_avg_{c}_last_15' for c in colunas_stats]
df_pre_model[colunas_novas] = df_pre_model[colunas_novas].fillna(0)

In [35]:
df_pre_model

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,matchup_id,p1_won,p2_won,total_h2h_matches,p1_h2h_wins,p2_h2h_wins,total_h2h_matches_surface,p1_h2h_wins_surface,p2_h2h_wins_surface,total_h2h_matches_last_10,p1_h2h_wins_last_10,p2_h2h_wins_last_10,total_h2h_matches_last_10_surf,p1_h2h_wins_last_10_surf,p2_h2h_wins_last_10_surf,p1_id,p2_id,p1_avg_ace_last_15,p1_avg_df_last_15,p1_avg_svpt_last_15,p1_avg_first_in_last_15,p1_avg_first_won_last_15,p1_avg_second_won_last_15,p1_avg_sv_gms_last_15,p1_avg_bp_saved_last_15,p1_avg_bp_faced_last_15,p2_avg_ace_last_15,p2_avg_df_last_15,p2_avg_svpt_last_15,p2_avg_first_in_last_15,p2_avg_first_won_last_15,p2_avg_second_won_last_15,p2_avg_sv_gms_last_15,p2_avg_bp_saved_last_15,p2_avg_bp_faced_last_15
0,2008-451,Doha,Hard,32,A,20071231,4,104098,8.0,NaN,Dmitry Tursunov,R,185.0,RUS,25.0,103656,NaN,NaN,Albert Montanes,R,175.0,ESP,27.0,6-2 7-5,3,R32,81.0,9.0,1.0,67.0,44.0,34.0,10.0,10.0,3.0,4.0,5.0,2.0,65.0,40.0,29.0,8.0,10.0,2.0,6.0,34.0,853.0,46.0,681.0,103656_104098,0,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,103656,104098,4.000000,1.500000,46.500000,31.500000,25.000000,8.000000,8.000000,1.500000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2008-451,Doha,Hard,32,A,20071231,5,104918,3.0,NaN,Andy Murray,R,190.0,GBR,20.6,103694,NaN,NaN,Olivier Rochus,R,168.0,BEL,26.9,6-0 6-2,3,R32,79.0,5.0,1.0,38.0,21.0,16.0,11.0,7.0,0.0,1.0,1.0,5.0,73.0,38.0,24.0,6.0,7.0,11.0,17.0,11.0,1755.0,48.0,661.0,103694_104918,0,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,103694,104918,4.000000,1.500000,46.500000,31.500000,25.000000,8.000000,8.000000,1.500000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2008-891,Chennai,Hard,32,A,20071231,2,104330,NaN,Q,Rajeev Ram,R,193.0,USA,23.7,103393,NaN,NaN,Yuri Schukin,R,188.0,KAZ,28.5,7-6(6) 7-6(2),3,R32,113.0,9.0,1.0,89.0,63.0,47.0,14.0,12.0,2.0,3.0,4.0,2.0,81.0,52.0,36.0,19.0,12.0,0.0,1.0,253.0,160.0,122.0,363.0,103393_104330,0,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,103393,104330,5.000000,2.285714,83.428571,53.428571,38.000000,16.285714,11.571429,5.428571,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2008-451,Doha,Hard,32,A,20071231,26,104918,3.0,NaN,Andy Murray,R,190.0,GBR,20.6,102563,NaN,NaN,Thomas Johansson,R,180.0,SWE,32.7,7-6(4) 6-0,3,QF,88.0,11.0,2.0,55.0,35.0,28.0,15.0,9.0,0.0,0.0,2.0,2.0,61.0,44.0,24.0,9.0,9.0,2.0,5.0,11.0,1755.0,62.0,583.0,102563_104918,0,1,1,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,102563,104918,5.000000,2.285714,83.428571,53.428571,38.000000,16.285714,11.571429,5.428571,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2008-451,Doha,Hard,32,A,20071231,1,103786,1.0,NaN,Nikolay Davydenko,R,178.0,RUS,26.5,103684,NaN,Q,Benedikt Dorsch,R,178.0,GER,26.9,6-3 6-0,3,R32,76.0,1.0,3.0,45.0,41.0,29.0,0.0,7.0,2.0,3.0,2.0,2.0,59.0,43.0,18.0,8.0,8.0,7.0,13.0,4.0,2825.0,215.0,191.0,103684_103786,0,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,103684,103786,4.545455,1.727273,65.090909,38.181818,28.363636,15.909091,10.909091,2.454545,4.272727,5.000000,1.000000,38.000000,21.000000,16.000000,11.000000,7.000000,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53167,2026-520,Roland Garros,Clay,128,G,20260525,219,100644,2.0,NaN,Alexander Zverev,R,198.0,GER,29.0,207411,NaN,NaN,Jesper De Jong,R,180.0,NED,25.9,7-6(3) 6-4 6-1,5,R16,134.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5705.0,106.0,580.0,100644_207411,1,0,2,2.0,0.0,2.0,2.0,0.0,3.0,2.0,1.0,3.0,2.0,1.0,100644,207411,5.266667,2.533333,82.333333,49.133333,34.133333,18.466667,12.666667,3.933333,6.266667,3.666667,2.533333,77.200000,47.666667,32.466667,14.466667,11.733333,4.666667,7.533333
53168,2026-520,Roland Garros,Clay,128,G,20260525,218,212588,27.0,NaN,Rafael Jodar,U,NaN,ESP,19.6,105807,NaN,NaN,Pablo Carreno Busta,R,188.0,ESP,34.8,4-6 4-6 6-1 6-2 6-2,5,R16,221.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0,1461.0,89.0,685.0,105807_212588,0,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,105807,212588,3.733333,2.533333,78.533333,47.666667,33.000000,15.600000,12.000000,4.600000,7.266667,5.266667,2.600000,82.400000,49.000000,34.333333,18.400000,12.733333,4.000000,6.400000
53169,2026-520,Roland Garros,Clay,128,G,20260525,217,211663,28.0,NaN,Joao Fonseca,R,185.0,BRA,19.7,134770,15.0,NaN,Casper Ruud,R,183.0,NOR,27.4,7-5 7-6(8) 5-7 6-2,5,R16,235.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,1435.0,16.0,2275.0,134770_211663,0,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,134770,211663,3.666667,2.666667,79.333333,47.000000,32.733333,16.200000,12.200000,4.066667,6.866667,5.333333,2.466667,80.866667,48.133333,33.533333,17.733333,12.400000,4.266667,6.733333
53170,2026-520,Roland Garros,Clay,128,G,20260525,115,210097,5.0,NaN,Ben Shelton,L,193.0,USA,23.6,210017,NaN,NaN,Daniel Merida Aguilar,R,188.0,ESP,21.6,6-3 6-3 6-4,5,R128,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,4070.0,86.0,696.0,210017_210097,0,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,210017,210097,3.533333,2.466667,81.866667,49.066667,33.333333,16.266667,12.466667,4.200000,7.266667,5.000000,2.400000,79.000000,47.933333,32.866667,16.600000,11.866667,4.800000,7.333333
53171,2026-520,Roland Garros,Clay,128,G,20260525,111,126207,19.0,NaN,Frances Tiafoe,R,188.0,USA,28.3,208118,NaN,NaN,Eliot Spizzirri,R,183.0,USA,24.4,6-3 6-7(5) 6-4 6-3,5,R128,176.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,1905.0,91.0,660.0,126207_208118,1,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,126207,208118,4.733333,2.533333,75.533333,45.066667,31.600000,16.266667,11.466667,4.400000,6.800000,3.533333,2.333333,78.933333,47.866667,32.733333,15.533333,12.200000,3.866667,6.800000

In [36]:
# Convertemos a coluna para o formato de data do Pandas (caso já não esteja)
df_pre_model['tourney_date'] = pd.to_datetime(df_pre_model['tourney_date'], format='%Y%m%d')

# Filtramos a base: guardamos apenas as partidas de 2011 em diante para treinar o modelo
df_final_para_modelo = df_pre_model[df_pre_model['tourney_date'].dt.year >= 2011].reset_index(drop=True)

In [37]:
df_final_para_modelo['tourney_date'] = pd.to_datetime(df_final_para_modelo['tourney_date'])
df_treino = df_final_para_modelo[df_final_para_modelo['tourney_date'].dt.year >= 2011].copy()
# --- 1. SEPARAÇÃO DAS DUAS METADES (ESPELHAMENTO COMPLETO) ---

# Metade 1: P1 é o Vencedor (Target = 1)
metade_vitoria = pd.DataFrame()
metade_vitoria['target'] = np.ones(len(df_treino))

# Características de Contexto/Perfil (P1 = Vencedor, P2 = Perdedor)
metade_vitoria['p1_age'] = df_treino['winner_age']
metade_vitoria['p2_age'] = df_treino['loser_age']
metade_vitoria['p1_rank'] = df_treino['winner_rank']
metade_vitoria['p2_rank'] = df_treino['loser_rank']
metade_vitoria['p1_rank_pts'] = df_treino['winner_rank_points']
metade_vitoria['p2_rank_pts'] = df_treino['loser_rank_points']

# Histórico Total de Confrontos (H2H)
metade_vitoria['p1_h2h_wins_all'] = df_treino['p1_h2h_wins']
metade_vitoria['p2_h2h_wins_all'] = df_treino['p2_h2h_wins']
metade_vitoria['p1_h2h_wins_surf'] = df_treino['p1_h2h_wins_surface']
metade_vitoria['p2_h2h_wins_surf'] = df_treino['p2_h2h_wins_surface']

# Histórico Recente de Confrontos (Últimas 10 no piso - que calculamos depois)
metade_vitoria['p1_h2h_wins_recent_surf'] = df_treino['p1_h2h_wins_last_10_surf']
metade_vitoria['p2_h2h_wins_recent_surf'] = df_treino['p2_h2h_wins_last_10_surf']

# Médias Móveis de Performance (Últimas 15 partidas)
for col in colunas_stats:
    metade_vitoria[f'p1_avg_{col}'] = df_treino[f'p1_avg_{col}_last_15']
    metade_vitoria[f'p2_avg_{col}'] = df_treino[f'p2_avg_{col}_last_15']


# Metade 2: P1 é o Perdedor (Target = 0) - INVERTENDO TUDO
metade_derrota = pd.DataFrame()
metade_derrota['target'] = np.zeros(len(df_treino))

# Características de Contexto/Perfil (Invertido)
metade_derrota['p1_age'] = df_treino['loser_age']
metade_derrota['p2_age'] = df_treino['winner_age']
metade_derrota['p1_rank'] = df_treino['loser_rank']
metade_derrota['p2_rank'] = df_treino['winner_rank']
metade_derrota['p1_rank_pts'] = df_treino['loser_rank_points']
metade_derrota['p2_rank_pts'] = df_treino['winner_rank_points']

# Histórico Total de Confrontos (Invertido)
metade_derrota['p1_h2h_wins_all'] = df_treino['p2_h2h_wins']
metade_derrota['p2_h2h_wins_all'] = df_treino['p1_h2h_wins']
metade_derrota['p1_h2h_wins_surf'] = df_treino['p2_h2h_wins_surface']
metade_derrota['p2_h2h_wins_surf'] = df_treino['p1_h2h_wins_surface']

# Histórico Recente de Confrontos (Invertido)
metade_derrota['p1_h2h_wins_recent_surf'] = df_treino['p2_h2h_wins_last_10_surf']
metade_derrota['p2_h2h_wins_recent_surf'] = df_treino['p1_h2h_wins_last_10_surf']

# Médias Móveis de Performance (Invertido)
for col in colunas_stats:
    metade_derrota[f'p1_avg_{col}'] = df_treino[f'p2_avg_{col}_last_15']
    metade_derrota[f'p2_avg_{col}'] = df_treino[f'p1_avg_{col}_last_15']


# --- 2. JUNTAR AS DUAS METADES ---
base_modelagem = pd.concat([metade_vitoria, metade_derrota]).reset_index(drop=True)

# Trata possíveis rankings vazios (como jogadores novos que entram sem rank, coloca um valor alto tipo 999)
base_modelagem[['p1_rank', 'p2_rank']] = base_modelagem[['p1_rank', 'p2_rank']].fillna(999)
base_modelagem = base_modelagem.fillna(0)


# --- 3. AUTOMAÇÃO DA CRIAÇÃO DE TODAS AS DIFERENÇAS (O "PULO DO GATO") ---
# Em vez de fazer uma por uma, vamos pegar todos os pares de colunas p1_ e p2_ e calcular a diferença

# Lista com os nomes base de todas as características
recursos_base = ['age', 'rank', 'rank_pts', 'h2h_wins_all', 'h2h_wins_surf', 'h2h_wins_recent_surf'] + [f'avg_{col}' for col in colunas_stats]

for recurso in recursos_base:
    base_modelagem[f'diff_{recurso}'] = base_modelagem[f'p1_{recurso}'] - base_modelagem[f'p2_{recurso}']


# --- 4. SEPARAÇÃO FINAL (X e y) ---
y = base_modelagem['target']
X = base_modelagem.drop(columns=['target'])

print(f"Base de dados finalizada!")
print(f"Quantidade total de colunas de recursos (features) para o modelo: {X.shape[1]}")

Base de dados finalizada!
Quantidade total de colunas de recursos (features) para o modelo: 45

In [42]:
(X.head())

,p1_age,p2_age,p1_rank,p2_rank,p1_rank_pts,p2_rank_pts,p1_h2h_wins_all,p2_h2h_wins_all,p1_h2h_wins_surf,p2_h2h_wins_surf,p1_h2h_wins_recent_surf,p2_h2h_wins_recent_surf,p1_avg_ace,p2_avg_ace,p1_avg_df,p2_avg_df,p1_avg_svpt,p2_avg_svpt,p1_avg_first_in,p2_avg_first_in,p1_avg_first_won,p2_avg_first_won,p1_avg_second_won,p2_avg_second_won,p1_avg_sv_gms,p2_avg_sv_gms,p1_avg_bp_saved,p2_avg_bp_saved,p1_avg_bp_faced,p2_avg_bp_faced,diff_age,diff_rank,diff_rank_pts,diff_h2h_wins_all,diff_h2h_wins_surf,diff_h2h_wins_recent_surf,diff_avg_ace,diff_avg_df,diff_avg_svpt,diff_avg_first_in,diff_avg_first_won,diff_avg_second_won,diff_avg_sv_gms,diff_avg_bp_saved,diff_avg_bp_faced
0,29.2,26.7,32.0,57.0,1300.0,839.0,0.0,1.0,0.0,1.0,0.0,2.0,7.923077,6.500000,2.846154,2.916667,72.230769,75.916667,42.538462,45.000000,30.615385,32.083333,14.769231,15.583333,11.538462,11.833333,4.076923,4.666667,6.769231,7.333333,2.5,-25.0,461.0,-1.0,-1.0,-2.0,1.423077,-0.070513,-3.685897,-2.461538,-1.467949,-0.814103,-0.294872,-0.589744,-0.564103
1,22.1,27.4,48.0,79.0,940.0,622.0,0.0,0.0,0.0,0.0,0.0,1.0,6.333333,6.307692,3.083333,2.538462,75.750000,68.307692,44.250000,38.923077,31.500000,27.230769,15.750000,14.076923,11.750000,10.769231,4.750000,3.615385,7.500000,6.923077,-5.3,-31.0,318.0,0.0,0.0,-1.0,0.025641,0.544872,7.442308,5.326923,4.269231,1.673077,0.980769,1.134615,0.576923
2,28.3,25.4,8.0,138.0,3665.0,398.0,0.0,0.0,0.0,0.0,0.0,1.0,6.750000,4.416667,3.000000,2.916667,76.833333,72.750000,45.583333,40.750000,32.333333,28.083333,15.666667,15.083333,12.000000,11.166667,4.583333,3.583333,7.416667,7.166667,2.9,-130.0,3267.0,0.0,0.0,-1.0,2.333333,0.083333,4.083333,4.833333,4.250000,0.583333,0.833333,1.000000,0.250000
3,26.3,28.3,5.0,8.0,5580.0,3665.0,2.0,3.0,2.0,2.0,2.0,3.0,6.750000,8.076923,3.000000,3.461538,76.833333,74.846154,45.583333,43.846154,32.333333,31.000000,15.666667,14.538462,12.000000,11.461538,4.583333,4.230769,7.416667,7.461538,-2.0,-3.0,1915.0,-1.0,0.0,-1.0,-1.326923,-0.461538,1.987179,1.737179,1.333333,1.128205,0.538462,0.352564,-0.044872
4,29.5,27.1,53.0,9.0,877.0,3240.0,2.0,3.0,1.0,3.0,1.0,4.0,5.461538,6.750000,3.230769,3.250000,68.384615,77.583333,37.692308,44.000000,26.076923,31.333333,14.076923,16.416667,10.538462,11.833333,4.076923,3.750000,7.615385,7.000000,2.4,44.0,-2363.0,-1.0,-2.0,-3.0,-1.288462,-0.019231,-9.198718,-6.307692,-5.256410,-2.339744,-1.294872,0.326923,0.615385